# Generated by Django 4.0.3 on 2022-03-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_sessionplayerperiod_good_one_consumption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterset',
            old_name='private_chat',
            new_name='enable_chat',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='period_length',
        ),
    ]
