# Generated by Django 4.0.3 on 2022-03-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_parametersetperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='survey_link',
            field=models.CharField(default='', max_length=1000, verbose_name='Survey Link'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='survey_required',
            field=models.BooleanField(default=False, verbose_name='Survey Complete'),
        ),
        migrations.AlterField(
            model_name='parametersetperiod',
            name='period_number',
            field=models.IntegerField(default=1, verbose_name='Period Number'),
        ),
        migrations.AddConstraint(
            model_name='parametersetperiod',
            constraint=models.UniqueConstraint(fields=('period_number', 'parameter_set'), name='unique_parameter_set_period'),
        ),
    ]
