# Generated by Django 4.0.3 on 2022-03-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_parametersetperiod_survey_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='period_type',
            field=models.CharField(choices=[('No Pay', 'No Pay'), ('Fixed Pay', 'Fixed Pay'), ('Individual Pay', 'Individual Pay'), ('Group Pay', 'Group Pay')], default='No Pay', max_length=100),
        ),
    ]
