# Generated by Django 4.0.3 on 2022-03-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_parametersetperiod_period_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetZoneMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_minutes', models.IntegerField(default=1, verbose_name='Max Zone Minutes')),
                ('label', models.CharField(default='min to min', max_length=20, verbose_name='Label Shown')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_zone_minutes', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Zone Minutes',
                'verbose_name_plural': 'Parameter Zone Minutes',
                'ordering': ['zone_minutes'],
            },
        ),
        migrations.AddConstraint(
            model_name='parametersetzoneminutes',
            constraint=models.UniqueConstraint(fields=('zone_minutes', 'parameter_set'), name='unique_parameter_set_zone_minutes'),
        ),
    ]
