# Generated by Django 4.0.3 on 2022-03-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_parametersetzoneminutes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetzoneminutes',
            options={'ordering': ['zone_minutes'], 'verbose_name': 'Parameter Set Zone Minutes', 'verbose_name_plural': 'Parameter Set Zone Minutes'},
        ),
        migrations.AlterField(
            model_name='parametersetzoneminutes',
            name='zone_minutes',
            field=models.IntegerField(default=1440, verbose_name='Max Zone Minutes'),
        ),
    ]
