# Generated by Django 4.0.3 on 2022-03-15 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_parametersetzoneminutes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetperiod',
            options={'ordering': ['period_number'], 'verbose_name': 'Parameter Set Period', 'verbose_name_plural': 'Parameter Set Periods'},
        ),
        migrations.CreateModel(
            name='ParameterSetPeriodIndividualPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_period_individual_pays_a', to='main.parametersetperiod')),
                ('parameter_set_zone_minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_period_individual_pays_b', to='main.parametersetzoneminutes')),
            ],
            options={
                'verbose_name': 'Parameter Set Period Individual Pay',
                'verbose_name_plural': 'Parameter Set Indvidual Payments',
            },
        ),
        migrations.AddConstraint(
            model_name='parametersetperiodindividualpay',
            constraint=models.UniqueConstraint(fields=('parameter_set_period', 'parameter_set_zone_minutes'), name='unique_parameter_set_individual_pay'),
        ),
    ]
