# Generated by Django 4.0.3 on 2022-03-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_parametersetperiodpayments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParameterSetPeriodPayments',
            new_name='ParameterSetPeriodPayment',
        ),
    ]
