# Generated by Django 4.0.3 on 2022-03-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_parametersetperiodpayments_parametersetperiodpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetperiodpayment',
            options={'ordering': ['parameter_set_zone_minutes__zone_minutes'], 'verbose_name': 'Parameter Set Period Pay', 'verbose_name_plural': 'Parameter Set Payments'},
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='enable_chat',
            field=models.BooleanField(default=False, verbose_name='Private Chat'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='show_instructions',
            field=models.BooleanField(default=False, verbose_name='Show Instructions'),
        ),
        migrations.AlterField(
            model_name='parametersetperiodpayment',
            name='parameter_set_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_period_pays_a', to='main.parametersetperiod'),
        ),
        migrations.AlterField(
            model_name='parametersetperiodpayment',
            name='parameter_set_zone_minutes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_period_pays_b', to='main.parametersetzoneminutes'),
        ),
    ]
