# Generated by Django 4.0.3 on 2022-03-16 21:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_parametersetperiodpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='notice_text',
            field=tinymce.models.HTMLField(default='Notice Text Here', verbose_name='Notice Text'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='show_notice',
            field=models.BooleanField(default=False, verbose_name='Show Notice'),
        ),
    ]
