# Generated by Django 3.2.12 on 2022-03-17 18:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_parametersetperiod_notice_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='minimum_wrist_minutes',
            field=models.IntegerField(default=1080),
        ),
        migrations.AlterField(
            model_name='parametersetperiod',
            name='notice_text',
            field=tinymce.models.HTMLField(blank=True, default='Notice Text Here', verbose_name='Notice Text'),
        ),
    ]
