# Generated by Django 3.2.12 on 2022-03-18 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220318_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionperiod',
            name='period_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
