# Generated by Django 3.2.12 on 2022-03-18 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_sessionperiod_period_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='current_period',
        ),
        migrations.AddField(
            model_name='sessionperiod',
            name='parameter_set_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_periods_b', to='main.parametersetperiod'),
        ),
    ]
