# Generated by Django 3.2.12 on 2022-03-18 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20220318_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='time_remaining',
        ),
        migrations.RemoveField(
            model_name='sessionplayerchat',
            name='time_remaining',
        ),
    ]
