# Generated by Django 3.2.12 on 2022-03-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20220318_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='timer_running',
        ),
    ]
