# Generated by Django 3.2.12 on 2022-03-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_session_timer_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='show_graph',
            field=models.BooleanField(default=False, verbose_name='Show Graph'),
        ),
    ]
