# Generated by Django 3.2.12 on 2022-03-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_parametersetperiod_show_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='graph_end_period_number',
            field=models.IntegerField(default=1, verbose_name='Graph End Period'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='graph_start_period_number',
            field=models.IntegerField(default=1, verbose_name='Graph Start Period'),
        ),
    ]
