# Generated by Django 3.2.12 on 2022-03-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20220322_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='pay_group',
            field=models.IntegerField(default=1, verbose_name='Pay Group'),
        ),
    ]
