# Generated by Django 3.2.12 on 2022-03-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_parametersetperiod_pay_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetperiod',
            old_name='pay_group',
            new_name='pay_block',
        ),
    ]
