# Generated by Django 3.2.12 on 2022-03-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_pay_group_parametersetperiod_pay_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionplayerperiod',
            name='earnings',
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='earnings_group',
            field=models.IntegerField(default=0, verbose_name='Individual Earnings'),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='earnings_individual',
            field=models.IntegerField(default=0, verbose_name='Individual Earnings'),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_birthday',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_heart_time_series',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_min_heart_rate_zone_bpm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_minutes_fairly_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_minutes_heart_cardio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_minutes_heart_fat_burn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_minutes_heart_out_of_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_minutes_heart_peak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_minutes_lightly_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_minutes_sedentary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_minutes_very_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_on_wrist_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_sleep_time_series',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='sleep_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='zone_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
