# Generated by Django 3.2.12 on 2022-03-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220322_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='graph_y_max',
            field=models.IntegerField(default=75, verbose_name='Graph: Y Max'),
        ),
    ]
