# Generated by Django 3.2.12 on 2022-03-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_parameterset_graph_y_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='check_in',
            field=models.BooleanField(default=False, verbose_name='Checked In'),
        ),
        migrations.AlterField(
            model_name='sessionplayerperiod',
            name='sleep_minutes',
            field=models.IntegerField(default=0, verbose_name='Sleep Minutes'),
        ),
        migrations.AlterField(
            model_name='sessionplayerperiod',
            name='zone_minutes',
            field=models.IntegerField(default=0, verbose_name='Zone Minutes'),
        ),
    ]
