# Generated by Django 3.2.12 on 2022-03-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20220331_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetperiod',
            old_name='show_graph',
            new_name='show_graph_1',
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='graph_2_end_period_number',
            field=models.IntegerField(default=1, verbose_name='Graph 2 End Period'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='graph_2_start_period_number',
            field=models.IntegerField(default=1, verbose_name='Graph 2 Start Period'),
        ),
        migrations.AlterField(
            model_name='parametersetperiod',
            name='graph_1_end_period_number',
            field=models.IntegerField(default=1, verbose_name='Graph 1 End Period'),
        ),
        migrations.AlterField(
            model_name='parametersetperiod',
            name='graph_1_start_period_number',
            field=models.IntegerField(default=1, verbose_name='Graph 1 Start Period'),
        ),
    ]
