# Generated by Django 3.2.12 on 2022-04-05 22:12

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_sessionplayerperiod_fitbit_heart_time_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayerperiod',
            name='fitbit_heart_time_series',
            field=models.JSONField(blank=True, decoder=django.core.serializers.json.DjangoJSONEncoder, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='sessionplayerperiod',
            name='fitbit_sleep_time_series',
            field=models.JSONField(blank=True, decoder=django.core.serializers.json.DjangoJSONEncoder, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
