# Generated by Django 3.2.12 on 2022-04-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20220405_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='fitbit_last_synced',
            field=models.DateTimeField(default=None, null=True, verbose_name='FitBit Last Synced'),
        ),
    ]
