# Generated by Django 3.2.12 on 2022-04-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_sessionplayer_fitbit_last_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='fitbit_device',
            field=models.CharField(default='', max_length=100, verbose_name='FitBit Device'),
        ),
    ]
