# Generated by Django 3.2.12 on 2022-04-12 22:10

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_sessionplayer_fitbit_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionplayer',
            options={'ordering': ['session', 'player_number'], 'verbose_name': 'Session Player', 'verbose_name_plural': 'Session Players'},
        ),
        migrations.RemoveField(
            model_name='sessionplayerperiod',
            name='fitbit_birthday',
        ),
        migrations.RemoveField(
            model_name='sessionplayerperiod',
            name='fitbit_height',
        ),
        migrations.RemoveField(
            model_name='sessionplayerperiod',
            name='fitbit_weight',
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_profile',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
