# Generated by Django 3.2.12 on 2022-04-12 22:20

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20220412_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='fitbit_activities',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
