# Generated by Django 3.2.12 on 2022-04-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_sessionplayerperiod_fitbit_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='software_version',
            field=models.CharField(default='1.00', max_length=100),
        ),
    ]
