# Generated by Django 3.2.12 on 2022-04-21 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_sessionplayerperiod_survey_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='activity_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Subject Activity Key'),
        ),
    ]
