# Generated by Django 3.2.12 on 2022-04-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_sessionplayerperiod_activity_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='channel_name',
            field=models.CharField(default='', max_length=1000, verbose_name='Django channels key'),
        ),
        migrations.AlterField(
            model_name='parametersetperiod',
            name='survey_required',
            field=models.BooleanField(default=False, verbose_name='Survey Required'),
        ),
    ]
