# Generated by Django 3.2.12 on 2022-04-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20220422_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='check_in_forced',
            field=models.BooleanField(default=False, verbose_name='Checked In Forced'),
        ),
        migrations.AlterField(
            model_name='sessionplayerperiod',
            name='earnings_group',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Group Earnings'),
        ),
    ]
