# Generated by Django 3.2.12 on 2022-04-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_sessionplayerperiod_back_pull'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetplayer',
            options={'ordering': ['id'], 'verbose_name': 'Parameter Set Player', 'verbose_name_plural': 'Parameter Set Players'},
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='enable_chat',
            field=models.BooleanField(default=False, verbose_name='Enable Chat'),
        ),
    ]
