# Generated by Django 3.2.12 on 2022-04-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20220428_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionplayerchat',
            name='chat_type',
        ),
        migrations.RemoveField(
            model_name='sessionplayerchat',
            name='session_player_recipients',
        ),
    ]
