# Generated by Django 3.2.12 on 2022-05-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_parametersetperiod_survey_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetplayer',
            name='id_label',
            field=models.CharField(default='1', max_length=10, verbose_name='ID Label'),
        ),
    ]
