# Generated by Django 3.2.12 on 2022-05-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_parametersetplayer_id_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='consent_form',
            field=models.CharField(default='file_name.pdf', max_length=100, verbose_name='Consent Form File Name'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='consent_form_required',
            field=models.BooleanField(default=False, verbose_name='Consent Form Required'),
        ),
        migrations.AddField(
            model_name='sessionplayer',
            name='consent_form_required',
            field=models.BooleanField(default=False, verbose_name='Consent Form Required'),
        ),
    ]
