# Generated by Django 3.2.12 on 2022-05-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20220504_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='display_block',
        ),
    ]
