# Generated by Django 3.2.12 on 2022-05-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_sessionplayerperiod_fitbit_resting_heart_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionplayerperiod',
            old_name='fibit_age',
            new_name='fitbit_age',
        ),
    ]
