# Generated by Django 3.2.12 on 2022-05-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_rename_fibit_age_sessionplayerperiod_fitbit_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiodpayment',
            name='no_pay_percent',
            field=models.IntegerField(default=0, verbose_name='No Pay Fitbit Percent'),
        ),
        migrations.AlterField(
            model_name='parametersetperiodpayment',
            name='group_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Group Payment'),
        ),
        migrations.AlterField(
            model_name='parametersetperiodpayment',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Individual Payment'),
        ),
    ]
