# Generated by Django 3.2.12 on 2022-05-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20220509_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetperiodpayment',
            name='no_pay_percent',
            field=models.IntegerField(default=0, verbose_name='No Pay Fitbit Percent'),
        ),
    ]
