# Generated by Django 3.2.12 on 2022-05-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_parametersetperiodpayment_no_pay_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='earnings_no_pay_percent',
            field=models.IntegerField(default=0, verbose_name='No Pay Fitbit Percent'),
        ),
    ]
