# Generated by Django 3.2.12 on 2022-05-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_sessionplayerperiod_earnings_no_pay_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='group_size',
            field=models.IntegerField(default=2, verbose_name='Group Size'),
        ),
    ]
