# Generated by Django 4.1.3 on 2022-12-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_parameterset_group_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionplayerperiod',
            name='fitbit_sleep_time_series',
        ),
        migrations.RemoveField(
            model_name='sessionplayerperiod',
            name='sleep_minutes',
        ),
    ]
