# Generated by Django 4.1.4 on 2022-12-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_helpdocsubject_helpdocsubjectset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdocsubject',
            name='help_doc_subject_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_docs_subject', to='main.helpdocsubjectset'),
        ),
        migrations.AlterField(
            model_name='parametersetperiod',
            name='survey_link',
            field=models.CharField(blank=True, default='https://www.google.com', max_length=1000, verbose_name='Survey Link'),
        ),
    ]
