# Generated by Django 4.1.4 on 2022-12-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_alter_helpdocsubject_help_doc_subject_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='help_doc_subject_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_sets_b', to='main.helpdocsubjectset'),
        ),
    ]
