# Generated by Django 4.1.4 on 2023-01-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_parameterset_help_doc_subject_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetPayBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_block_type', models.CharField(choices=[('No Pay', 'No Pay'), ('Average', 'Average'), ('Total', 'Total')], default='No Pay', max_length=100)),
                ('pay_block_number', models.IntegerField(default=1, verbose_name='Pay Block Number')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_pay_blocks_a', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Pay Block',
                'verbose_name_plural': 'Parameter Set Pay Blocks',
                'ordering': ['pay_block_number'],
            },
        ),
        migrations.CreateModel(
            name='ParameterSetPayBlockPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_minutes', models.IntegerField(default=1440, verbose_name='Max Zone Minutes')),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Individual Payment')),
                ('group_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Group Payment')),
                ('no_pay_percent', models.IntegerField(default=0, verbose_name='No Pay Fitbit Percent')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set_pay_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_pay_block_payments_a', to='main.parametersetpayblock')),
            ],
            options={
                'verbose_name': 'Parameter Set Pay Block Payment',
                'verbose_name_plural': 'arameter Set Pay Block Payments',
                'ordering': ['zone_minutes'],
            },
        ),
        migrations.AddConstraint(
            model_name='parametersetpayblockpayment',
            constraint=models.UniqueConstraint(fields=('parameter_set_pay_block', 'zone_minutes'), name='unique_parameter_set_pay_block_payment'),
        ),
        migrations.AddConstraint(
            model_name='parametersetpayblock',
            constraint=models.UniqueConstraint(fields=('pay_block_number', 'parameter_set'), name='unique_parameter_set_pay_block'),
        ),
    ]
