# Generated by Django 4.1.4 on 2023-01-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_parameterset_json_for_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetpayblock',
            name='pay_block_type',
            field=models.CharField(choices=[('No Activity Pay', 'No Activity Pay'), ('Block Pay', 'Block Pay'), ('Daily Pay', 'Daily Pay')], default='No Activity Pay', max_length=100),
        ),
    ]
