# Generated by Django 4.1.4 on 2023-01-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_parametersetpayblock_fixed_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetpayblock',
            name='pay_block_type',
            field=models.CharField(choices=[('Fixed Pay Only', 'Fixed Pay Only'), ('Block Pay', 'Block Pay'), ('Earn Fitbit', 'Earn Fitbit')], default='Fixed Pay Only', max_length=100),
        ),
    ]
