# Generated by Django 4.1.4 on 2023-01-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_alter_parametersetpayblock_pay_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='parameter_set_pay_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_periods_b', to='main.parametersetpayblock'),
        ),
    ]
