# Generated by Django 4.1.4 on 2023-01-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_parameterset_json_for_subject2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='json_for_subject2',
        ),
    ]
