# Generated by Django 4.1.4 on 2023-01-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_alter_parametersetpayblock_pay_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='average_pay_block_zone_minutes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Average Zone Minutes'),
        ),
    ]
