# Generated by Django 4.1.4 on 2023-01-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_sessionplayerperiod_earnings_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetperiod',
            name='period_type',
        ),
    ]
