# Generated by Django 4.1.4 on 2023-01-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_remove_parametersetperiod_period_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterSetPeriodPayment',
        ),
    ]
