# Generated by Django 4.1.4 on 2023-01-17 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_sessionperiod_is_last_period_in_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='player_key_backup',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Player Key Backup'),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='player_key',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Player Key'),
        ),
    ]
