# Generated by Django 4.1.4 on 2023-01-17 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_sessionplayer_player_key_backup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='recruiter_id_private',
            field=models.IntegerField(default=0, verbose_name='Recruiter ID Private'),
        ),
        migrations.AddField(
            model_name='sessionplayer',
            name='recruiter_id_public',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Recruiter ID Public'),
        ),
    ]
