# Generated by Django 4.1.4 on 2023-01-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_sessionplayer_recruiter_id_private_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetpayblockpayment',
            options={'ordering': ['zone_minutes'], 'verbose_name': 'Parameter Set Pay Block Payment', 'verbose_name_plural': 'Parameter Set Pay Block Payments'},
        ),
    ]
