# Generated by Django 4.1.4 on 2023-01-20 21:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_alter_parametersetpayblockpayment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='completion_message',
            field=tinymce.models.HTMLField(blank=True, default='Notice Text Here', verbose_name='Notice Text'),
        ),
    ]
