# Generated by Django 4.1.4 on 2023-02-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_alter_parameterset_completion_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='note',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Note'),
        ),
    ]
