# Generated by Django 4.1.4 on 2023-02-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_sessionplayer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='soft_delete',
            field=models.BooleanField(default=False, verbose_name='Soft Delete'),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled'),
        ),
    ]
