# Generated by Django 4.1.4 on 2023-03-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_sessionplayer_soft_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='age_warning',
            field=models.IntegerField(default=25, verbose_name='Age Warning'),
        ),
    ]
