# Generated by Django 4.1.7 on 2023-03-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_parameterset_age_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='reconnection_limit',
            field=models.IntegerField(default=25, verbose_name='Age Warning'),
        ),
    ]
