# Generated by Django 5.2.9 on 2025-12-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_sessionplayer_fitbit_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionperiod',
            name='paused',
            field=models.BooleanField(default=False, verbose_name='Paused'),
        ),
    ]
