# Generated by Django 5.2.9 on 2025-12-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_sessionperiod_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetpayblock',
            name='pay_block_type',
            field=models.CharField(choices=[('Fixed Pay Only', 'Fixed Pay Only'), ('Block Pay Group', 'Block Pay Group'), ('Block Pay Individual', 'Block Pay Individual'), ('Earn Fitbit', 'Earn Fitbit'), ('Block Pay Competition', 'Block Pay Competition')], default='Fixed Pay Only', max_length=100),
        ),
    ]
