# Generated by Django 5.2.9 on 2025-12-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_alter_parametersetpayblock_pay_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetpayblock',
            name='group_assignment_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Fixed', 'Fixed'), ('Sorted', 'Sorted')], default='Fixed', max_length=100),
        ),
    ]
