# Generated by Django 5.2.9 on 2025-12-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_parametersetpayblock_group_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='color_assignment_type',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Dynamic', 'Dynamic')], default='Fixed', max_length=100, verbose_name='Color Assignment Type'),
        ),
    ]
