# Generated by Django 5.2.9 on 2025-12-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_parameterset_color_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='current_group_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Group Number this Period'),
        ),
    ]
