# Generated by Django 5.2.9 on 2026-01-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_sessionplayerperiod_current_group_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='show_history',
            field=models.BooleanField(default=False, verbose_name='Show History'),
        ),
    ]
