# Generated by Django 5.2.8 on 2026-01-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_parameterset_show_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='partner_string',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Partner String'),
        ),
    ]
