# Generated by Django 5.2.9 on 2026-01-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_parameterset_partner_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetpayblock',
            name='pay_block_type',
            field=models.CharField(choices=[('Fixed Pay Only', 'Fixed Pay Only'), ('Block Pay Group', 'Block Pay Group'), ('Block Pay Individual', 'Block Pay Individual'), ('Earn Fitbit', 'Earn Fitbit'), ('Block Pay Competition', 'Block Pay Competition'), ('No Pay', 'No Pay')], default='Fixed Pay Only', max_length=100),
        ),
    ]
