# Generated by Django 5.2.9 on 2026-01-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_alter_parametersetpayblock_pay_block_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetperiod',
            name='parameter_set_pay_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_periods_b', to='main.parametersetpayblock'),
        ),
    ]
