# Generated by Django 5.2.11 on 2026-02-05 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0105_alter_parametersetperiod_parameter_set_pay_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mfa_hash', models.CharField(blank=True, max_length=50, null=True, verbose_name='Multi-factor Hash')),
                ('mfa_required', models.BooleanField(default=True, verbose_name='Multi-factor Required')),
                ('mfa_setup_complete', models.BooleanField(default=False, verbose_name='Multi-factor Setup Complete')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='Login Success')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_login_attempts', to='main.profile')),
            ],
            options={
                'verbose_name': 'Profile Login Attempt',
                'verbose_name_plural': 'Profile Login Attempts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
