# Generated by Django 5.2.11 on 2026-02-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_profile_profileloginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='reconnection_limit',
            field=models.IntegerField(default=10, verbose_name='Reconnection Limit'),
        ),
    ]
