# Generated by Django 5.2.11 on 2026-03-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_alter_parameterset_reconnection_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='graph_y_max_slider',
            field=models.IntegerField(default=300, verbose_name='Graph: Y Max Slider Default'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='graph_y_max',
            field=models.IntegerField(default=75, verbose_name='Graph: Y Max Default'),
        ),
    ]
