# Generated by Django 5.2.11 on 2026-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_parameterset_graph_y_max_slider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='current_y_scale_max',
            field=models.IntegerField(default=50, verbose_name='Current Y Scale Max'),
        ),
    ]
