# Generated by Django 5.2.12 on 2026-03-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_sessionplayer_current_y_scale_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='zone_minutes_from_heart_rate',
            field=models.IntegerField(default=0, verbose_name='Zone Minutes Observed'),
        ),
    ]
